version: '2'
services:
  simplejavaapp-app:
    image: simplejavaapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://simplejavaapp-mysql:3306/simplejavaapp?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://simplejavaapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://simplejavaapp-elasticsearch:9200
    ports:
      - 8080:8080
  simplejavaapp-mysql:
    extends:
      file: mysql.yml
      service: simplejavaapp-mysql
  simplejavaapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: simplejavaapp-elasticsearch
